### ISSUE TITLE
Add info about thread-safety to README

### ISSUE THREAD

**Issue by nevmerzhitsky** [Rebilly/rebilly-php#429]
Hello guys!

Please, describe here and add to the README info about the thread-safety of the `Rebilly\Client` class. Is it depend on the value of "httpHandler" option of the class? Particularly when the `Rebilly\Http\GuzzleAdapter` used?

**Comment by 2e3s** [comment]
Hello, I think thread safety is an excessive information in context of PHP to add it to the readme.
If you do not share the same client object between threads (which is recommended), it should be alright because there are no writeable static variables in our code (I don't know about the underlying libraries like Guzzle). Otherwise, nothing is guaranteed, we put no effort into ensuring any thread safety.

**Comment by 2e3s** [comment]
I think thread safety is an excessive information in context of PHP to add it to the readme.
If you do not share the same client object between threads (which is recommended), it should be alright because there are no writeable static variables in our code (I don't know about the underlying libraries like Guzzle). Otherwise, nothing is guaranteed, we put no effort into ensuring any thread safety.
